#File Path
MTB_DATA: '../data/Mtb/'
Pheno_DATA: '../data/pheno/'
Metdata: '../data/pheno/metadata_Sinergia_final_dataset_human_bac_genome_available_QCed.txt'
HLA_Data: '../data/HLA/FourDigits/'
SCRATCH_DIR: '../scratch/'
RESULTS_DIR: '../results/'
host_bfile: '../data/Genotyping_WGS/TBDAR.WGS.Imputed.GWASReady'
PASCAL_path: '/home/zmxu/Software/PASCAL/'
Del_tbl: '../data/Mtb/binary_table_genes_Sinergia_final_dataset_human_bac_genome_available.txt'

#Pathogen Variant Type Settings
SIFT: 'False'
Burden: 'False'
Deletion: 'False'
Stratified: 'False'
Analysis_Type: 'G2G' #G2G or xrayscore
Homo_Only: 'True'
Het_Thresh: 10 #Percent reads supporting ALT, in percentage
tool: 'PLINK'

#Pathogen Settings
Pathogen_MAC_pPCA: 15
Pathogen_MAC_AA_Lineage: 15
Pathogen_MAC_AA: 15
Pathogen_Missing: 0.05
N_pPC: 0

#Host Settings
Host_MAF: 0.05
N_PC: 3
Covars_to_incl: 'patient_sex'
