#File Path
MTB_DATA: '../data/Mtb/'
Pheno_DATA: '../data/pheno/'
Metdata: '../data/pheno/metadata_Sinergia_final_dataset_human_bac_genome_available_QCed.txt'
HLA_Data: '../data/HLA/FourDigits/'
SCRATCH_DIR: '../scratch/'
RESULTS_DIR: '../results/'
host_bfile: '../data/Genotyping_WGS/TBDAR.WGS.Imputed.GWASReady'
PASCAL_path: '/home/zmxu/Software/PASCAL/'

#Pathogen Variant Type Settings
SIFT: 'False'
Burden: 'True'
Deletion: 'False'
Analysis_Type: 'G2G' #G2G or xrayscore
Homo_Only: 'True'
tool: 'PLINK'

#Pathogen Settings
Pathogen_MAC_pPCA: 10
Pathogen_MAC_AA_Lineage: 10
Pathogen_MAC_AA: 10
N_pPC: 0
Stratified: 'False'

#Host Settings
Host_MAF: 0.05
N_PC: 3
Covars_to_incl: 'patient_sex'
